site_name: MolPy

repo_name: MolPy
repo_url: https://github.com/Roy-Kid/molpy

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - toc.follow
    - toc.integrate
    - navigation.top

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/startup.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - pymdownx.superfences

nav:
  - Home: index.md
  - Tutorial: 
    - Getting Start: tutorial/index.md
    - System: tutorial/system.md

  - About: about.md