site_name: molpy
repo_name: molcrafts/molpot
repo_url: https://github.com/molcrafts/molpy

copyright: Copyright &copy; 2024 - 2025 Jichen Li

theme:
  name: material
  palette:
    - scheme: default
      primary: "teal"
      accent: "light blue"
      background: "#f9f9f9"
      text: "#333333"
      surface: "#ffffff"
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: "teal"
      accent: "light blue"
      background: "#f3f3f3"  # 更深一点的浅灰色
      text: "#444444"  # 较深的文本灰
      surface: "#fefefe"  # 几乎白色
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings

nav:
  - Home: index.md
  - Getting Started: 
    - Core:
      - Box: start/core/box.md
      - Forcefield: start/core/forcefield.md
      - Frame: start/core/frame.md
      - Trajectory: start/core/trajectory.md
      - Region: start/core/region.md
      - Structure: start/core/struct.md
      - System: start/core/system.md
  - API Reference:
    - Core:
      - Box: reference/core/box.md
      - Forcefield: reference/core/forcefield.md
      - Frame: reference/core/frame.md
      - Trajectory: reference/core/trajectory.md
      - Region: reference/core/region.md
      - Structure: reference/core/struct.md
      - System: reference/core/system.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.blocks.caption

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

