[project]
name = "molcrafts-molpy"

version = "0.0.1"

authors = [
    { name = "Roy Kid", email = "lijichen365@gmail.com" }
]

description = "Fundamental package for computational chemistry in Python"

readme = "README.md"

requires-python = ">=3.11"

classifiers = [
    "License :: OSI Approved :: BSD License",
    "Development Status :: 1 - Planning",
    'Intended Audience :: Science/Research',
    'Intended Audience :: Developers',
    'Programming Language :: C',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3 :: Only',
    'Programming Language :: Python :: Implementation :: CPython',
    'Topic :: Software Development',
    'Topic :: Scientific/Engineering',
    'Typing :: Typed',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: POSIX',
    'Operating System :: Unix',
    'Operating System :: MacOS',
]

license = {file = "LICENSE"}

dependencies = [
  "numpy",  # https://github.com/numpy/numpy
  "igraph",  # https://github.com/igraph/python-igraph
  "pint",  # https://github.com/hgrecco/pint
  "chemfiles",  # https://github.com/chemfiles/chemfiles.py
]

[project.optional-dependencies]
dev = ["pytest", "ase"]
test = ["pytest", "coverage"]

[project.urls]
Homepage = "https://github.com/MolCrafts/molpot"
Issues = "https://github.com/MolCrafts/molpot/issues"

[build-system]
requires = [
    "setuptools",
]
build-backend = "setuptools.build_meta"
