[project]
name = "molpy"
version = "0.0.1"
dependencies = [
    "numpy",
    "pint",
    "chemfiles"
    "igraph"
]

[build-system]
requires = [
    "setuptools",
]
build-backend = "setuptools.build_meta"
